import easydict

KEYS = easydict.EasyDict()
KEYS.ALEXNET = "alexnet"
KEYS.BIGGAN = "biggan"
KEYS.DINO_VITS8 = "dino_vits8"
KEYS.RESNET152 = "resnet152"

KEYS.IMAGENET = "imagenet"
KEYS.PLACES365 = "places365"

KEYS.ALEXNET_IMAGENET = f"{KEYS.ALEXNET}/{KEYS.IMAGENET}"
KEYS.BIGGAN_IMAGENET = f"{KEYS.BIGGAN}/{KEYS.IMAGENET}"
KEYS.DINO_VITS8_IMAGENET = f"{KEYS.DINO_VITS8}/{KEYS.IMAGENET}"
KEYS.RESNET152_IMAGENET = f"{KEYS.RESNET152}/{KEYS.IMAGENET}"

KEYS.ALEXNET_PLACES365 = f"{KEYS.ALEXNET}/{KEYS.PLACES365}"
KEYS.RESNET152_PLACES365 = f"{KEYS.RESNET152}/{KEYS.PLACES365}"
KEYS.BIGGAN_PLACES365 = f"{KEYS.BIGGAN}/{KEYS.PLACES365}"

KEYS.GENERATORS = "gen"
KEYS.CLASSIFIERS = "cls"
KEYS.BASE = "base"
KEYS.NOT_ALEXNET_IMAGENET = f"not-{KEYS.ALEXNET}-{KEYS.IMAGENET}"
KEYS.NOT_ALEXNET_PLACES365 = f"not-{KEYS.ALEXNET}-{KEYS.PLACES365}"
KEYS.NOT_RESNET152_IMAGENET = f"not-{KEYS.RESNET152}-{KEYS.IMAGENET}"
KEYS.NOT_RESNET152_PLACES365 = f"not-{KEYS.RESNET152}-{KEYS.PLACES365}"
KEYS.NOT_BIGGAN_IMAGENET = f"not-{KEYS.BIGGAN}-{KEYS.IMAGENET}"
KEYS.NOT_BIGGAN_PLACES365 = f"not-{KEYS.BIGGAN}-{KEYS.PLACES365}"

# Different partitions of MILANNOTATIONS based on the generalization
# experiments from the original paper.
DATASET_GROUPINGS = {
    KEYS.BASE: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.CLASSIFIERS: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
    ),
    KEYS.GENERATORS: (
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.IMAGENET: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.RESNET152_IMAGENET,
        KEYS.BIGGAN_IMAGENET,
    ),
    KEYS.PLACES365: (
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.ALEXNET: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
    ),
    KEYS.RESNET152: (
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
    ),
    KEYS.BIGGAN: (
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_ALEXNET_IMAGENET: (
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_ALEXNET_PLACES365: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_RESNET152_IMAGENET: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_RESNET152_PLACES365: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.BIGGAN_IMAGENET,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_BIGGAN_IMAGENET: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_PLACES365,
    ),
    KEYS.NOT_BIGGAN_PLACES365: (
        KEYS.ALEXNET_IMAGENET,
        KEYS.ALEXNET_PLACES365,
        KEYS.RESNET152_IMAGENET,
        KEYS.RESNET152_PLACES365,
        KEYS.BIGGAN_IMAGENET,
    ),
}

TRAIN_TEST_PAIRS = {
    KEYS.CLASSIFIERS: KEYS.GENERATORS,
    KEYS.GENERATORS: KEYS.CLASSIFIERS,
    KEYS.IMAGENET: KEYS.PLACES365,
    KEYS.PLACES365: KEYS.IMAGENET,
    KEYS.ALEXNET: KEYS.RESNET152,
    KEYS.RESNET152: KEYS.ALEXNET,
    KEYS.BASE: KEYS.DINO_VITS8_IMAGENET,
    KEYS.NOT_ALEXNET_IMAGENET: KEYS.ALEXNET_IMAGENET,
    KEYS.NOT_ALEXNET_PLACES365: KEYS.ALEXNET_PLACES365,
    KEYS.NOT_RESNET152_IMAGENET: KEYS.RESNET152_IMAGENET,
    KEYS.NOT_RESNET152_PLACES365: KEYS.RESNET152_PLACES365,
    KEYS.NOT_BIGGAN_IMAGENET: KEYS.BIGGAN_IMAGENET,
    KEYS.NOT_BIGGAN_PLACES365: KEYS.BIGGAN_PLACES365,
}

WITHIN_NETWORK = [
    KEYS.ALEXNET_IMAGENET,
    KEYS.ALEXNET_PLACES365,
    KEYS.BIGGAN_IMAGENET,
    KEYS.BIGGAN_PLACES365,
    KEYS.RESNET152_IMAGENET,
    KEYS.RESNET152_PLACES365,
]
